# Generated by Django 5.1.4 on 2025-09-05 08:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text="Recipient's phone number.", max_length=15)),
                ('message', models.TextField(help_text='Message content.')),
                ('request_id', models.CharField(help_text='Beem API request ID.', max_length=50)),
                ('status', models.CharField(default='PENDING', help_text='SMS delivery status.', max_length=20)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Time when the SMS was sent.')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_sms', to='members.churchmember')),
            ],
        ),
    ]
