# Generated by Django 5.1.4 on 2025-09-05 08:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the news', max_length=255)),
                ('content', models.TextField(help_text='Detailed content of the news')),
                ('bible_reference', models.TextField(blank=True, help_text='Bible reference lines related to the news', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the news was created')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Name of the commenter (optional)', max_length=100, null=True)),
                ('comment_text', models.TextField(help_text='The comment content')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the comment was made')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='news.news')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], help_text='Type of media', max_length=10)),
                ('file', models.FileField(help_text='Upload an image, video, or document', upload_to='news/media/')),
                ('news', models.ForeignKey(help_text='Associated news post', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='news.news')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session or unique identifier for user', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the like was added')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='news.news')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('news', 'session_id')},
            },
        ),
    ]
