# Generated by Django 5.1.4 on 2025-09-05 08:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('properties', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique category name (e.g., 'Construction Projects', 'Fundraising', etc.).", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description or overview of this category.', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this category was first created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when this category was last updated.')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OfferingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Unique name of the offering category (e.g., 'Sunday Mass Offering', 'Fundraising', etc.).", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Additional details or notes about this offering category.', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this offering category was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when this offering category was last updated.')),
            ],
            options={
                'verbose_name': 'Offering Category',
                'verbose_name_plural': 'Offering Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_type', models.CharField(choices=[('DIOCESAN', 'Special Diocesan contributions'), ('JIMBO', 'Jimbo contributions'), ('FELLOWSHIP', 'Fellowship contributions')], default='JIMBO', help_text='Type of special contribution (Diocesan, Jimbo, or Parish).', max_length=20)),
                ('name', models.CharField(help_text='The name of the special contribution (e.g., Church Renovation Fund, Charity Drive, etc.).', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the purpose or details of the special contribution.', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the special contribution record was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the special contribution record was last updated.')),
            ],
            options={
                'verbose_name': 'Special Contribution',
                'verbose_name_plural': 'Special Contributions',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], help_text='Select the month for this expenditure.', max_length=15)),
                ('date_taken', models.DateTimeField(default=django.utils.timezone.now, help_text='Date when the expenditure was taken (default is now).')),
                ('expenditure_amount', models.DecimalField(decimal_places=2, help_text='Amount of money spent.', max_digits=12)),
                ('expenditure_purpose', models.CharField(blank=True, help_text='Brief purpose or title for this expenditure (optional).', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or remarks regarding this expenditure (optional).', null=True)),
                ('receipt', models.FileField(blank=True, help_text='Upload a receipt or supporting document for this expenditure (PDF, image, etc.).', null=True, upload_to='receipt_uploads/')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this record was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when this record was last updated.')),
                ('category', models.ForeignKey(help_text='The category under which this expenditure falls.', on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='finance.category')),
                ('year', models.ForeignKey(help_text='The year this expenditure is associated with.', on_delete=django.db.models.deletion.PROTECT, related_name='expenditures', to='settings.year')),
            ],
            options={
                'verbose_name': 'Expenditure',
                'verbose_name_plural': 'Expenditures',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='FacilityRenting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentor_name', models.CharField(help_text='Name of the person renting the asset.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Rental amount in Tanzanian Shillings (TZS)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_rented', models.DateField(default=django.utils.timezone.now, help_text='Date when the asset was rented.')),
                ('end_date', models.DateField(blank=True, help_text='Date when the rental period ends.', null=True)),
                ('purpose', models.TextField(blank=True, help_text='Purpose for renting the facility.', null=True)),
                ('receipt_id', models.CharField(editable=False, help_text='Automatically generated receipt ID (5 numbers + 5 uppercase letters).', max_length=10, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the renting record was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the renting record was last updated.')),
                ('property_rented', models.ForeignKey(help_text='The church asset that is being rented.', on_delete=django.db.models.deletion.CASCADE, related_name='facility_rentings', to='properties.churchasset')),
                ('year', models.ForeignKey(help_text='The year this renting belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='facility_rentings', to='settings.year')),
            ],
            options={
                'verbose_name': 'Facility Renting',
                'verbose_name_plural': 'Facility Rentings',
                'ordering': ['-date_rented'],
            },
        ),
        migrations.CreateModel(
            name='Offerings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField(default=django.utils.timezone.now, help_text='The date offering was given. Displays the day of the week.')),
                ('service_time', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Night', 'Night')], help_text='The service during which the offering was collected.', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total amount of money collected.', max_digits=10)),
                ('mass_name', models.CharField(help_text='The name of the mass during which the offering was collected.', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Additional details or notes about this offering.', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='The date and time when this offering was recorded.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='The date and time when this offering was last updated.')),
                ('collected_by', models.ForeignKey(help_text='The church member who collected the offering.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings_collected', to='members.churchmember')),
                ('offering_category', models.ForeignKey(help_text='Category under which this offering is classified.', on_delete=django.db.models.deletion.CASCADE, related_name='offerings', to='finance.offeringcategory')),
                ('outstation', models.ForeignKey(help_text='The outstation where this offering was collected.', on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='settings.outstation')),
                ('recorded_by', models.ForeignKey(help_text='The church member who recorded the offering.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offerings_recorded', to='members.churchmember')),
                ('year', models.ForeignKey(blank=True, help_text='The year in which this offering was recorded.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='settings.year')),
            ],
        ),
        migrations.CreateModel(
            name='Pledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelope_number', models.CharField(help_text='Envelope number used for the pledge.', max_length=50)),
                ('pledge_amount', models.DecimalField(decimal_places=2, help_text='The pledged amount.', max_digits=10)),
                ('pledge_for_construction', models.DecimalField(decimal_places=2, help_text='The amount pledged specifically for construction.', max_digits=10)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], help_text='The month in which the pledge was made.', max_length=10)),
                ('date_given', models.DateField(help_text='The date when the pledge was given.')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='The date and time when the pledge record was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='The date and time when the pledge record was last updated.')),
                ('member', models.ForeignKey(help_text='The church member making the pledge.', on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='members.churchmember')),
                ('year', models.ForeignKey(help_text='The year in which the pledge was made.', on_delete=django.db.models.deletion.CASCADE, related_name='pledges', to='settings.year')),
            ],
        ),
        migrations.CreateModel(
            name='DonationItemFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='The period associated with this donation (e.g., Q1 2024, January 2024, etc.).', max_length=100)),
                ('mass_name', models.CharField(help_text='The name of the mass or event where this donation was made.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='The amount obtained from this donation.', max_digits=12)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or remarks related to the donation.', null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the donation item fund was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the donation item fund was last updated.')),
                ('year', models.ForeignKey(help_text='The year this donation item fund belongs to.', on_delete=django.db.models.deletion.PROTECT, related_name='donation_item_funds', to='settings.year')),
                ('contribution_type', models.ForeignKey(help_text='The special contribution this donation item fund belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='donation_item_funds', to='finance.specialcontribution')),
            ],
            options={
                'verbose_name': 'Donation Item Fund',
                'verbose_name_plural': 'Donation Item Funds',
                'ordering': ['-date_created'],
            },
        ),
    ]
