# Generated by Django 5.1.4 on 2025-09-05 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], help_text='Select the month for this report.', max_length=20)),
                ('number_of_evangelists', models.PositiveIntegerField(help_text='Number of evangelists.')),
                ('number_of_local_congregations', models.PositiveIntegerField(help_text='Total local congregations in the parish.')),
                ('local_congregations_lords_table', models.PositiveIntegerField(help_text='Number of congregations where you administered the Lord’s Table.')),
                ('baptized_male', models.PositiveIntegerField(default=0, help_text='Number of males baptized.')),
                ('baptized_female', models.PositiveIntegerField(default=0, help_text='Number of females baptized.')),
                ('returned_male', models.PositiveIntegerField(default=0, help_text='Number of returning male Christians.')),
                ('returned_female', models.PositiveIntegerField(default=0, help_text='Number of returning female Christians.')),
                ('marriages_solemnized', models.PositiveIntegerField(default=0, help_text='Total number of marriages officiated.')),
                ('membership_transfer_sessions_count', models.PositiveIntegerField(default=0, help_text='How many times you taught membership transfer sessions.')),
                ('membership_transfer_sessions_where', models.TextField(blank=True, help_text='Where those membership transfer sessions were conducted.')),
                ('number_of_christians', models.PositiveIntegerField(default=0, help_text='Number of Christians in total.')),
                ('number_of_cell_groups', models.PositiveIntegerField(default=0, help_text='Number of cell groups in the parish.')),
                ('church_projects', models.TextField(blank=True, help_text='Details of ongoing church/parish projects.')),
                ('number_of_joined_christians', models.PositiveIntegerField(default=0, help_text='Number of new Christians who joined.')),
                ('number_of_deceased_christians', models.PositiveIntegerField(default=0, help_text='Number of Christians who passed on to glory.')),
                ('number_of_separated_christians', models.PositiveIntegerField(default=0, help_text='Number of Christians who left (separated from) the church.')),
                ('number_of_relocated_christians', models.PositiveIntegerField(default=0, help_text='Number of Christians who relocated.')),
                ('average_income_this_month', models.DecimalField(decimal_places=2, default=0.0, help_text='Average total monthly income.', max_digits=12)),
                ('number_of_schools', models.PositiveIntegerField(default=0, help_text='Number of schools within this parish.')),
                ('parish_meetings', models.TextField(blank=True, help_text='Specify committees and when they met.')),
                ('growth_explanations', models.TextField(blank=True, help_text='Explanations fostering spiritual, numerical, and economic growth.')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Date and time this report was created (set automatically).')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Date and time this report was last updated (auto).')),
                ('year', models.ForeignKey(help_text='Select the reporting year.', on_delete=django.db.models.deletion.PROTECT, to='settings.year')),
            ],
        ),
        migrations.CreateModel(
            name='DatesOfServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(help_text='Date of the service.')),
                ('pastor_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates_of_services', to='pastor.pastorreport')),
            ],
        ),
        migrations.CreateModel(
            name='VisitedLocalCongregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('congregation_name', models.CharField(help_text='Name of the local congregation/sub-parish visited.', max_length=100)),
                ('pastor_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_congregations', to='pastor.pastorreport')),
            ],
        ),
    ]
