# Generated by Django 5.1.4 on 2025-09-05 08:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the asset.', max_length=255)),
                ('asset_type', models.CharField(choices=[('Building', 'Building'), ('Furniture', 'Furniture'), ('Electronics', 'Electronics'), ('Vehicle', 'Vehicle'), ('Stationery', 'Stationery'), ('Equipment', 'Equipment'), ('Consumables', 'Consumables')], help_text='Type of asset.', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Short description of the asset.', null=True)),
                ('acquisition_date', models.DateField(blank=True, help_text='Date the asset was acquired (optional).', null=True)),
                ('quantity_name', models.CharField(choices=[('Pieces', 'Pieces'), ('Boxes', 'Boxes'), ('Packets', 'Packets'), ('Bundles', 'Bundles'), ('Sets', 'Sets'), ('Rolls', 'Rolls'), ('Pads', 'Pads'), ('Reams', 'Reams'), ('Dozens', 'Dozens'), ('Liters', 'Liters'), ('Units', 'Units'), ('Pairs', 'Pairs'), ('Square meters', 'Square meters'), ('Shelves', 'Shelves'), ('Cubic meters', 'Cubic meters'), ('Kits', 'Kits'), ('Batteries', 'Batteries'), ('Packs', 'Packs'), ('Fleets', 'Fleets'), ('Plots', 'Plots'), ('Blocks', 'Blocks'), ('Complexes', 'Complexes'), ('Towers', 'Towers'), ('Halls', 'Halls'), ('Rooms', 'Rooms'), ('Floors', 'Floors')], help_text='Unit of measurement (e.g., dozen, set, piece, etc.).', max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of units.')),
                ('status', models.CharField(choices=[('Good', 'Good'), ('Needs Repair', 'Needs Repair'), ('Damaged', 'Damaged'), ('Sold', 'Sold'), ('Donated', 'Donated')], help_text='Current condition of the asset.', max_length=20)),
                ('value', models.DecimalField(decimal_places=2, help_text='Estimated value of the asset (in currency).', max_digits=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Date and time when the asset was added.')),
            ],
            options={
                'verbose_name': 'Church Asset',
                'verbose_name_plural': 'Church Assets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChurchAssetMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload an image of the church asset.', upload_to='church_assets/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, help_text='The date and time this media was uploaded.')),
                ('church_asset', models.ForeignKey(help_text='The asset this media file is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='media', to='properties.churchasset')),
            ],
            options={
                'verbose_name': 'Church Asset Media',
                'verbose_name_plural': 'Church Asset Media',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
