# Generated by Django 5.1.4 on 2025-09-05 08:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(help_text='Latitude coordinate of the church')),
                ('longitude', models.FloatField(help_text='Longitude coordinate of the church')),
                ('altitude', models.FloatField(blank=True, help_text='Altitude (optional, will be auto-calculated if left blank)', null=True)),
                ('is_active', models.BooleanField(default=False, help_text='Mark this location as the active church location')),
            ],
        ),
        migrations.CreateModel(
            name='OutStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outstation_id', models.PositiveIntegerField(blank=True, help_text='Randomly generated 6-digit ID for the outstation.', null=True, unique=True)),
                ('name', models.CharField(help_text='Name of the outstation.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Short description of the outstation.', null=True)),
                ('location', models.CharField(help_text='Physical location of the outstation.', max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the outstation was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the outstation was last updated.')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024'), (2025, '2025'), (2026, '2026'), (2027, '2027'), (2028, '2028'), (2029, '2029'), (2030, '2030'), (2031, '2031'), (2032, '2032'), (2033, '2033'), (2034, '2034'), (2035, '2035'), (2036, '2036'), (2037, '2037'), (2038, '2038'), (2039, '2039'), (2040, '2040'), (2041, '2041'), (2042, '2042'), (2043, '2043'), (2044, '2044'), (2045, '2045'), (2046, '2046'), (2047, '2047'), (2048, '2048'), (2049, '2049'), (2050, '2050'), (2051, '2051'), (2052, '2052'), (2053, '2053'), (2054, '2054'), (2055, '2055'), (2056, '2056'), (2057, '2057'), (2058, '2058'), (2059, '2059'), (2060, '2060'), (2061, '2061'), (2062, '2062'), (2063, '2063'), (2064, '2064'), (2065, '2065'), (2066, '2066'), (2067, '2067'), (2068, '2068'), (2069, '2069'), (2070, '2070'), (2071, '2071'), (2072, '2072'), (2073, '2073'), (2074, '2074'), (2075, '2075'), (2076, '2076'), (2077, '2077'), (2078, '2078'), (2079, '2079'), (2080, '2080')], help_text='Select a year from 2020 to 2080.', unique=True)),
                ('is_current', models.BooleanField(default=False, help_text='Set this year as the current year.')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the year was added.')),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_id', models.PositiveIntegerField(blank=True, help_text='7-digit unique Cell ID', null=True, unique=True)),
                ('name', models.CharField(help_text='Name of the cell.', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the cell.', null=True)),
                ('location', models.CharField(help_text='Physical location of the cell.', max_length=255)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp when the cell was created.')),
                ('date_updated', models.DateTimeField(auto_now=True, help_text='Timestamp when the cell was last updated.')),
                ('outstation', models.ForeignKey(help_text='Outstation this cell belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='settings.outstation')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
