# Generated by Django 5.1.4 on 2025-09-05 08:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leaders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvangelistReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children_count', models.PositiveIntegerField(help_text='Number of children present.')),
                ('adults_count', models.PositiveIntegerField(help_text='Number of adults present.')),
                ('count_10000', models.PositiveIntegerField(default=0, help_text='Number of 10,000\xa0TZS notes.')),
                ('count_5000', models.PositiveIntegerField(default=0, help_text='Number of 5,000\xa0TZS notes.')),
                ('count_2000', models.PositiveIntegerField(default=0, help_text='Number of 2,000\xa0TZS notes.')),
                ('count_1000', models.PositiveIntegerField(default=0, help_text='Number of 1,000\xa0TZS notes.')),
                ('count_500', models.PositiveIntegerField(default=0, help_text='Number of 500\xa0TZS coins.')),
                ('count_200', models.PositiveIntegerField(default=0, help_text='Number of 200\xa0TZS coins.')),
                ('count_100', models.PositiveIntegerField(default=0, help_text='Number of 100\xa0TZS coins.')),
                ('count_50', models.PositiveIntegerField(default=0, help_text='Number of 50\xa0TZS coins.')),
                ('date_given', models.DateField(default=django.utils.timezone.now, help_text='Date the offering was given (defaults to today).')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Evangelist Report',
                'verbose_name_plural': 'Evangelist Reports',
                'ordering': ['-date_given'],
            },
        ),
        migrations.CreateModel(
            name='ElderDuty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('elder', models.ForeignKey(help_text='Select an elder who was on duty.', limit_choices_to={'occupation': 'Elder'}, on_delete=django.db.models.deletion.PROTECT, related_name='elder_duties', to='leaders.leader')),
                ('evangelist_report', models.ForeignKey(help_text='The evangelist report this duty record belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='elder_duties', to='evangelist.evangelistreport')),
            ],
            options={
                'verbose_name': 'Elder on Duty',
                'verbose_name_plural': 'Elders on Duty',
                'unique_together': {('evangelist_report', 'elder')},
            },
        ),
    ]
