# Generated by Django 5.1.4 on 2025-09-05 08:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leader_id', models.CharField(blank=True, help_text='Unique 20‑character ID with 10 digits + 10 lowercase letters.', max_length=20, null=True, unique=True)),
                ('occupation', models.CharField(choices=[('Senior Pastor', 'Senior Pastor'), ('Associate Pastor', 'Associate Pastor'), ('Assistant Pastor', 'Assistant Pastor'), ('Youth Pastor', 'Youth Pastor'), ('Children’s Pastor', 'Children’s Pastor'), ('Evangelist', 'Evangelist'), ('Missionary', 'Missionary'), ('Chairperson', 'Chairperson'), ('Vice Chairperson', 'Vice Chairperson'), ('Secretary', 'Secretary'), ('Assistant Secretary', 'Assistant Secretary'), ('Board Chair', 'Board Chair'), ('Board Secretary', 'Board Secretary'), ('Elder', 'Elder'), ('Chief Elder', 'Chief Elder'), ('Deacon', 'Deacon'), ('Deaconess', 'Deaconess'), ('Steward', 'Steward'), ('Worship Leader', 'Worship Leader'), ('Choir Director', 'Choir Director'), ('Praise Team Leader', 'Praise Team Leader'), ('Sunday School Teacher', 'Sunday School Teacher'), ('Bible Study Leader', 'Bible Study Leader'), ('Small Group Leader', 'Small Group Leader'), ('Youth Coordinator', 'Youth Coordinator'), ('Women’s Ministry Leader', 'Women’s Ministry Leader'), ('Men’s Ministry Leader', 'Men’s Ministry Leader'), ('Prayer Coordinator', 'Prayer Coordinator'), ('Intercessory Leader', 'Intercessory Leader'), ('Outreach Coordinator', 'Outreach Coordinator'), ('Missions Coordinator', 'Missions Coordinator'), ('Social Ministry Leader', 'Social Ministry Leader'), ('Hospitality Coordinator', 'Hospitality Coordinator'), ('Ushering Coordinator', 'Ushering Coordinator'), ('Security Coordinator', 'Security Coordinator'), ('Maintenance Supervisor', 'Maintenance Supervisor'), ('Welfare Coordinator', 'Welfare Coordinator'), ('Media/Tech Team Lead', 'Media/Tech Team Lead'), ('Communications Officer', 'Communications Officer'), ('Church Treasurer', 'Church Treasurer'), ('Church Accountant', 'Church Accountant'), ('Administrator', 'Administrator'), ('Patron', 'Patron'), ('Matron', 'Matron'), ('Advisor', 'Advisor')], help_text='Role / office held within the church.', max_length=100)),
                ('start_date', models.DateField(help_text='Date this leader began serving.')),
                ('responsibilities', models.TextField(help_text='Key duties and ministry scope.')),
                ('time_in_service', models.CharField(blank=True, help_text="Human‑readable duration in service (e.g., '3\xa0years').", max_length=100, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when this record was created.')),
                ('church_member', models.OneToOneField(help_text='Select the church member who serves as a leader.', on_delete=django.db.models.deletion.CASCADE, related_name='leader', to='members.churchmember')),
                ('outstation', models.ForeignKey(blank=True, help_text='Out‑station assignment (required for Evangelists).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='settings.outstation')),
            ],
        ),
    ]
