# Generated by Django 5.1.4 on 2025-09-05 08:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or subject of the notification.', max_length=255)),
                ('message', models.TextField(help_text='Detailed message content of the notification.')),
                ('is_read', models.BooleanField(default=False, help_text='Has the notification been read?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp of when the notification was created.')),
                ('church_member', models.ForeignKey(help_text='Church member receiving the notification. Required field.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='members.churchmember')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
